version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered pre_build phase


  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed

  post_build:
    commands:
      - echo Build completed


artifacts:
  files:
    - target/fakeStoreAPI-0.0.1-SNAPSHOT.jar
    - Dockerfile
  discard-paths: no
