spring.application.name=fakestoreapi
fakestore.base-url=${FAKESTORE_URL:http://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com}
spring.datasource.url=${DB_URL:jdbc:sqlite:products.db}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.sqlite.JDBC}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.community.dialect.SQLiteDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=5000
jwt.secret=${JWT_SECRET:da9rsoON2eZ3V1PpsGrP3frFPxIPnuEW9ogyJaQ4VEc}
spring.security.user.name=
spring.security.user.password=