spring.application.name=fakestoreapi
fakestore.base-url=${FAKESTORE_URL:https://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com}
spring.datasource.url=${DB_URL:jdbc:sqlite:products.db}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.sqlite.JDBC}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.community.dialect.SQLiteDialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
server.port=${PORT:5000}
spring.security.user.name=
spring.security.user.password=
jwt.secret=${JWT_SECRET:}